spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/courses
    password: password
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:db/changelog-root.xml
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${EUREKA_HOST}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${EUREKA_PORT}/eureka    
server:
  port: ${SERVICE_PORT}
