spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
microservices:
  courses:
    url: http://courses-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
server:
  port: ${SERVICE_PORT}
